<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-TBG7DKGB" failures="2" tests="8" name="testngpack1.vericycreateacc" time="642.643" errors="0" timestamp="2023-02-02T19:14:33 IST" skipped="0">
  <testcase classname="testngpack1.vericycreateacc" name="verifycreateamazonacc" time="220.887"/>
  <system-out/>
  <testcase classname="testngpack1.vericycreateacc" name="verifycreateamazonacc" time="34.019"/>
  <system-out/>
  <testcase classname="testngpack1.vericycreateacc" name="verifyConditonofuselink" time="134.429"/>
  <system-out/>
  <testcase classname="testngpack1.vericycreateacc" name="verifyConditonofuselink" time="45.855"/>
  <system-out/>
  <testcase classname="testngpack1.vericycreateacc" name="verifyPrivacyNoticelink" time="13.845">
    <failure message="expected [Amazon.in PrivacyNotice - Amazon Customer Service] but found [Amazon.in Privacy Notice - Amazon Customer Service]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Amazon.in PrivacyNotice - Amazon Customer Service] but found [Amazon.in Privacy Notice - Amazon Customer Service]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at testngpack1.vericycreateacc.verifyPrivacyNoticelink(vericycreateacc.java:75)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- verifyPrivacyNoticelink -->
  <system-out/>
  <testcase classname="testngpack1.vericycreateacc" name="verifyPrivacyNoticelink" time="62.100">
    <failure message="expected [Amazon.in PrivacyNotice - Amazon Customer Service] but found [Amazon.in Privacy Notice - Amazon Customer Service]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Amazon.in PrivacyNotice - Amazon Customer Service] but found [Amazon.in Privacy Notice - Amazon Customer Service]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at testngpack1.vericycreateacc.verifyPrivacyNoticelink(vericycreateacc.java:75)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- verifyPrivacyNoticelink -->
  <system-out/>
  <testcase classname="testngpack1.vericycreateacc" name="verifyHelplink" time="66.788"/>
  <system-out/>
  <testcase classname="testngpack1.vericycreateacc" name="verifyHelplink" time="64.720"/>
  <system-out/>
</testsuite> <!-- testngpack1.vericycreateacc -->
